### PR TITLE
Optionally sanitize null bytes

### PR DESCRIPTION
**Pull request by jcoleman**
While null bytes are valid UTF-8, they can often cause similar wonkiness to invalidly encoded strings. For example, regardless of encoding, PostgreSQL does not accept null bytes in varchar/text columns. For that reason it's useful to be able to remove such strings from input to the application in many cases.

### CODE REVIEW

**Comment by jcoleman** [comment]
This implements the feature I requested in #74.

**Review by whitequark — APPROVED** [review]

**Comment by whitequark** [comment]
Thanks!

**Comment by jcoleman** [comment]
@whitequark Thanks so much for the super-fast response on this PR!

If I might trouble you a bit further: would it be possible to do a version bump (maybe to 2.0 since this changed the method signature of custom strategies) and release a new version? I'd love to get this deployed in production for us.

**Comment by davidwessman** [comment]
@jcoleman Could you add some information to the README for using this feature?

**Comment by jcoleman** [comment]
@davidwessman Sure! See #77.

**Pull request merged**
